# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_vhdl C:/Users/kvemishe/Documents/XRAYDetector/SOM/Development/NotExportedCLK/SOMClipIDELAY/SOMClipIDELAY.srcs/sources_1/imports/user/tb_NiFpgaSimulationModel.vhd
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/kvemishe/Documents/XRAYDetector/SOM/Development/NotExportedCLK/SOMClipIDELAY/SOMClipIDELAY.data/wt [current_project]
set_property parent.project_dir C:/Users/kvemishe/Documents/XRAYDetector/SOM/Development/NotExportedCLK/SOMClipIDELAY [current_project]
synth_design -top tb_NiFpgaSimulationModel -part xc7vx485tffg1157-1
write_checkpoint tb_NiFpgaSimulationModel.dcp
report_utilization -file tb_NiFpgaSimulationModel_utilization_synth.rpt -pb tb_NiFpgaSimulationModel_utilization_synth.pb
